- hosts: datanode
  
  tasks: 
         - debug:
                 msg: "Hadoop datanode configuration started"
         - name: Downloading jdk software
           get_url:
                   url: "https://shracker.tk/jdk-8u171-linux-x64.rpm"
                   dest: /root
           become: true

         - name: Downloading hadoop software
           get_url: 
                   url: "https://shracker.tk/hadoop-1.2.1-1.x86_64.rpm"
                   dest: /root
           become: true
           

         - name: Installing jdk software
           yum:
                 name: "/root/jdk-8u171-linux-x64.rpm"
                 state: present
                 disable_gpg_check: yes
           register: java
           become: true
         - debug:
                var: java.results

         - name: Installing hadoop software
           command: rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force
           register: hadoop
           become: true
         - debug:
                 var: hadoop

         - name: stopping previous datanode services
           command: hadoop-daemon.sh stop datanode

         - name: Deleting datanode directory if already exist
           command: "rm -rf  /dn1"

         - name: Creating namenode directory
           file:
                   path:  /dn1
                   state: directory
           become: true

         - name: Updating hdfs-site.xml file
           blockinfile:
                   path: /etc/hadoop/hdfs-site.xml
                   insertafter: "<configuration>"
                   block:
                        <property>
                        <name>dfs.data.dir</name>
                        <value>/dn1</value>
                        </property>
           become: true

         - name: Updating core-site.xml file
           blockinfile:
                   path: /etc/hadoop/core-site.xml
                   insertafter: "<configuration>"
                   block:
                        <property>
                        <name>fs.default.name</name>
                        <value>hdfs://172.31.11.27:9001</value>
                        </property>
           become: true           
   
         

         - name: starting datanode services
           command: hadoop-daemon.sh start datanode
           register: data_service
           become: true
         - debug: 
                 var: data_service.stdout

         - name: Checking datanode services
           command: jps
           register: jps_service
           become: true

         - debug:
                 var: jps_service.stdout

         - debug: 
                 msg: "Hadoop datanode configured successfully !!!!!"

