- hosts: mgrafana
  vars:
    - version: "2.18.1"
  tasks:
    - name: Install grafana
      yum:
        name:  https://dl.grafana.com/oss/release/grafana-8.0.4-1.x86_64.rpm
        state: present      

    - name: "Grafana server started"
      service:
        name: grafana-server
        enabled: true
        state: started

    - name: "Check if Grafana is accessible."
      uri:
        url: http://localhost:3000
        method: GET
        status_code: 200
