- hosts: jobtracker
  
  tasks: 
         - debug:
                 msg: "Job Tracker configuration started"
         - name: Downloading jdk software
           get_url:
                   url: "https://shracker.tk/jdk-8u171-linux-x64.rpm"
                   dest: /root
           become: true

         - name: Downloading hadoop software
           get_url: 
                   url: "https://shracker.tk/hadoop-1.2.1-1.x86_64.rpm"
                   dest: /root
           become: true
           

         - name: Installing jdk software
           yum:
                 name: "/root/jdk-8u171-linux-x64.rpm"
                 state: present
                 disable_gpg_check: yes
           register: java
           become: true
         - debug:
                var: java.results

         - name: Installing hadoop software
           command: rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force
           register: hadoop
           become: true
         - debug:
                 var: hadoop

         - name: stopping previous jobTracker services
           command: hadoop-daemon.sh stop jobtracker

         - name: Updating mapred-site.xml file
           blockinfile:
                   path: /etc/hadoop/mapred-site.xml
                   insertafter: "<configuration>"
                   block:
                        <property>
                        <name>mapred.job.tracker</name>
                        <value>0.0.0.0:9002</value>
                        </property>
           become: true    

         - name: starting jobtracker  services
           command: hadoop-daemon.sh start jobtracker
           register: job_service
           become: true
         - debug: 
                 var: job_service.stdout

         - name: Checking jobtracker services
           command: jps
           register: jps_service
           become: true

         - debug:
                 var: jps_service.stdout

         - debug: 
                 msg: "Job Tracker  configured successfully !!!!!"

         - name: computing cluster report
           command: hadoop job -list-active-trackers
           register: report
           become: true

         - debug:
                 var: report.stdout_lines
